# Rust formatting configuration

# Use stable features only
edition = "2021"

# Basic formatting
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"

# Imports
imports_granularity = "Crate"
reorder_imports = true
reorder_modules = true

# Code style
use_small_heuristics = "Default"
use_field_init_shorthand = true
use_try_shorthand = true

# Comments
wrap_comments = true
comment_width = 80
normalize_comments = true

# Misc
trailing_comma = "Vertical"
match_block_trailing_comma = true
force_multiline_blocks = false
