# Rust formatting configuration

# Use stable features only
edition = "2021"

# Basic formatting
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"

# Stable features only
reorder_imports = true
reorder_modules = true
use_small_heuristics = "Default"
use_field_init_shorthand = true
use_try_shorthand = true
match_block_trailing_comma = true
