// Regenerate the checked-in WalletConnect responder bundle (wc-bundle.js).
//
// The dig-wallet crate must build OFFLINE (CI has no npm), so the bundle is
// committed and `include_str!`-ed into the wallet UI page. Re-run this only when
// entry.js or the @walletconnect deps change:
//
//   cd crates/dig-wallet/wc && npm install && node build.mjs
//
// It produces ../src/wc-bundle.js — a single self-contained browser IIFE that
// exposes `window.DigWC`. No build.rs, no npm at crate-build time.

import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, "../src/wc-bundle.js");

await build({
  entryPoints: [resolve(here, "entry.js")],
  bundle: true,
  format: "iife",
  globalName: "DigWC",
  platform: "browser",
  target: ["chrome120"],
  minify: true,
  legalComments: "none",
  outfile: out,
  // sign-client pulls in libs that reference node globals; provide browser-safe
  // shims so the bundle runs in the renderer.
  define: { global: "globalThis", "process.env.NODE_ENV": '"production"' },
  banner: {
    js: "/* DIG WalletConnect responder bundle — generated by wc/build.mjs. Do not edit by hand. */",
  },
});

console.log("wrote", out);
